// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PromoEngine.Data;

#nullable disable

namespace PromoEngine.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251027200049_AddPhoneToSubmissionModel")]
    partial class AddPhoneToSubmissionModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PromoEngine.Models.PromoCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PromoCodes");
                });

            modelBuilder.Entity("PromoEngine.Models.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AcceptedGameRules")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AcceptedPrivacyPolicy")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("HashedEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HashedFirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HashedLastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HashedPhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsWinner")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PrizeType")
                        .HasColumnType("longtext");

                    b.Property<int>("PromoCodeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PromoCodeId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("PromoEngine.Models.WinningTimestamp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsClaimed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("TargetTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("WinnerSubmissionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WinnerSubmissionId");

                    b.ToTable("WinningTimestamps");
                });

            modelBuilder.Entity("PromoEngine.Models.Submission", b =>
                {
                    b.HasOne("PromoEngine.Models.PromoCode", "PromoCode")
                        .WithMany()
                        .HasForeignKey("PromoCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PromoCode");
                });

            modelBuilder.Entity("PromoEngine.Models.WinningTimestamp", b =>
                {
                    b.HasOne("PromoEngine.Models.Submission", "WinnerSubmission")
                        .WithMany()
                        .HasForeignKey("WinnerSubmissionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("WinnerSubmission");
                });
#pragma warning restore 612, 618
        }
    }
}
